development:
  adapter: postgresql
  encoding: utf8
  database: style_scout_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: style_scout_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: style_scout_production

cucumber:
  <<: *TEST